### PR TITLE
Add refactor a HoC to Render Prop component egghead.io video

### PR DESCRIPTION
**Pull request by andrewdelprete**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hey @andrewdelprete! Thanks! Maybe we could add a new section to the bottom for "Paid Content" or something 🤔 I think it's good to make it clear what's free and what's not (because everything else on this list is free).

Could you do that?

**Comment by andrewdelprete** [comment]
Hey @kentcdodds - It looks like your https://egghead.io/lessons/react-use-render-props-with-react video is PRO too right? Maybe we could put a `$` symbol next to paid content or make a new section like you said? thoughts?

**Comment by kentcdodds** [comment]
Doh! How'd _that_ get in there!? Yes, let's add a 💲next to everything that's paid. Do you mind? Thanks!

**Comment by andrewdelprete** [comment]
Sure thing!

**Comment by kentcdodds** [comment]
Ah, found it! Here's how it got there: https://github.com/jaredpalmer/awesome-react-render-props/commit/e367469da47c993da75aaa688d34ab9b00eff822 😅

**Comment by andrewdelprete** [comment]
@kentcdodds np! 👍

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by andrewdelprete** [comment]
Thanks for merging!

**Pull request merged**
