### PR TITLE
Added ReactI18nRouting library

### PR DESCRIPTION
**Pull request by benatespina**

### CODE REVIEW

**Comment by benatespina** [comment]
PR rebased!

**Review by kentcdodds — COMMENTED** [review]
Hi! Sorry, but I'm not sure which component there is the render prop component. Could you direct me to that?

**Comment by benatespina** [comment]
As it says in the documentation:
```
These strategies are implemented following the render props React's popular pattern. However this technique generates useless boilerplate so, we have decorated providers itself with High Order Component pattern to reduce unneeded code.```

https://github.com/FriendsOfECMAScript/ReactI18nRouting/blob/master/src/component/bridges/ReduxBrowserIntlProvider.js#L76

**Comment by benatespina** [comment]
As it says in the documentation:

> These strategies are implemented following the render props React's popular pattern. However this technique generates useless boilerplate so, we have decorated providers itself with High Order Component pattern to reduce unneeded code.

You can check inside the codebase that the BrowserIntlProvider strategies are implemented following render prop pattern.

https://github.com/FriendsOfECMAScript/ReactI18nRouting/blob/master/src/component/bridges/ReduxBrowserIntlProvider.js#L76

https://github.com/FriendsOfECMAScript/ReactI18nRouting/blob/master/src/component/bridges/LocalStorageBrowserIntlProvider.js#L53

https://github.com/FriendsOfECMAScript/ReactI18nRouting/blob/master/src/component/bridges/InMemoryBrowserIntlProvider.js#L57

So, if you want to use without HOC, the only way is via render prop.

**Pull request merged**
